### ISSUE TITLE
"unsupported/Eigen/CXX11/Tensor" file not found

### ISSUE THREAD

**Issue by YosukeHiguchi** [yjmade/ios_camera_object_detection#1]
I have followed the instruction and tried to build this project. But it it crashes with the error 
"'unsupported/Eigen/CXX11/Tensor' file not found". I would like some help as soon as possible.

**Comment by yjmade** [comment]
this is related to tensorflow compiling, please refer to this https://github.com/tensorflow/tensorflow/issues/4680 or post a issue on tensorflow project

**Comment by jboehler** [comment]
I need to change settings in Xcode -> Build Settings -> Header Search Paths (HEADER_SEARCH_PATHS): 
from $(SRCROOT)/../../makefile/downloads/eigen-latest
to $(SRCROOT)/../../makefile/downloads/eigen

and make sure you have included the Accelerate framework in the "Link Binary with Libraries" build phase of your project. That's where cblas_sgemm should be defined when you are building for iOS.

**Comment by macro-dadt** [comment]
@jboehler   unfortunately it not worked for me

**Comment by zachgrayio** [comment]
I know this issue is closed and more of a TF issue, but does anyone have any more thoughts on this? I'm seeing it too on ios.

**Comment by wenchengxucool** [comment]
tensorflow/tensorflow#4680 only have the Pi solution. Didn't work on iOS.
